In [13]:
import numpy as np

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(7)

array([0.6325555 , 0.93538852, 0.48130697, 0.11948848, 0.75733036,
       0.99709569, 0.07824368])

In [19]:
np.random.rand(5,5)

array([[0.06696118, 0.37915241, 0.63369431, 0.88580282, 0.81070564],
       [0.42452855, 0.37008226, 0.37326722, 0.51091028, 0.71875542],
       [0.82223701, 0.8765432 , 0.55389455, 0.14285312, 0.97850237],
       [0.6226082 , 0.40218147, 0.79977919, 0.54716557, 0.50430938],
       [0.14110639, 0.91106037, 0.76861635, 0.33555126, 0.2662798 ]])

In [20]:
np.random.randn(5)

array([ 0.50971884,  1.2733149 , -2.06236735, -1.67147197, -2.62908475])

In [21]:
np.random.randn(5,5)

array([[ 0.27825188,  0.63624406, -1.82792079, -1.95430487, -0.97392444],
       [-0.69279133,  1.24957649, -1.09018104,  0.07694183, -0.9624617 ],
       [-1.20216128, -0.36775201, -1.3345501 ,  0.39811412, -0.09326086],
       [-0.50564802, -0.99083602,  0.44442575,  0.99819457,  0.02837086],
       [-0.60283548,  0.24676142,  0.27324532, -0.71567341, -0.75373414]])

In [22]:
np.random.randint(5,500,80)

array([465, 398,  81,  30, 435, 166, 469,  69, 152, 393, 116, 140,  75,
       130,  50, 232, 337, 304, 310, 217, 319, 458, 154, 334, 432, 432,
       441, 484, 295, 460, 479, 382, 427, 208, 292, 243, 443, 371,  35,
       375,  23, 233, 497, 440, 104, 180, 234,  57, 449, 315, 171, 425,
       393, 297,  78,  61, 261, 305, 488,  21, 451,  48, 344,  54, 407,
       397, 428, 472,   8, 397, 275,  70, 376, 168, 310, 174, 318, 256,
       469, 201], dtype=int32)

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([ 6,  4, 25, 36, 13, 29,  8, 12, 47, 40], dtype=int32)

In [33]:
ranarr

array([ 6,  4, 25, 36, 13, 29,  8, 12, 47, 40], dtype=int32)

In [1]:
import numpy as np
my_list = [1, 2, 3]
arr = np.array(my_list) 
print(my_list)

[1, 2, 3]


In [2]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mat = np.array(my_matrix)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [8]:
np.random.rand(3) 

array([0.93066659, 0.39519375, 0.22628009])

In [9]:
np.random.rand(3) 

array([0.03584532, 0.38926956, 0.74046871])

In [11]:
import numpy as np
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
