In [25]:
import numpy as np 

In [26]:
arr = np.arange(0,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[8]

np.int64(8)

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [31]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr[0:5]=100

In [33]:
arr = np.arange(0,11)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
slice_of_arr=arr[0:6]

In [36]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [37]:
slice_of_arr[:]=99

In [38]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [39]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [40]:
arr_copy=arr.copy()

In [41]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [42]:
arr_copy[:]=100

In [43]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [44]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [1]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [2]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [3]:
arr_2d[0][0] #5

np.int64(5)

In [5]:
arr_2d[1,0] #20

np.int64(20)

In [6]:
arr_2d[2,0] #35

np.int64(35)

In [7]:
arr_2d[2,2] #45

np.int64(45)

### For practice
Try making a 5*10 array of numbers 049, and practice selecting different "chunks" or sections using slicing....

In [1]:
arr = np.arange(1,11)

In [2]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
bool_arr = arr > 5

In [6]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [7]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [8]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [10]:
arr[arr<3]

array([1, 2])

In [11]:
arr_2d =np.arange(50).reshape(5,10)

In [12]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [13]:
arr_2d[3,1:5]

array([31, 32, 33, 34])

In [14]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])